name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gtest manually
      run: git clone https://github.com/google/googletest && cd googletest && mkdir build && cd build && cmake .. && make && sudo make install
    - uses: actions/checkout@v3
    - name: make
      run: cd unittest;make


